---

- name: Install httpd and php modules on CentOS VM
  yum: name={{ item }} state=present update_cache=yes
  with_items:
  - httpd
  - php
  - php-mysql


- name: Start the httpd service
  become: yes
  service: state=started name=httpd  enabled=yes


- name: Ensure that file are included to httpd.conf
  lineinfile: dest=/etc/httpd/conf/httpd.conf  state=present  line='Include conf.d/*.conf'

  notify:
    - restart httpd

#------- copy virtual-host config file to vm-box --------#

- name: Create/Copy VirtualHost file for centos1.com
  copy: src=centos_vhost1.conf  dest=/etc/httpd/conf.d/{{ ogo1 }}.conf  owner=apache  group=apache  mode=0755

- name: Create/Copy VirtualHost file for centos2.com
  copy: src=centos_vhost2.conf  dest=/etc/httpd/conf.d/{{ ogo2 }}.conf  owner=apache  group=apache  mode=0755
 

#------- create a log directory/file ---------#

- name: Create centos1.com directory for logs
  file: path=/var/log/httpd/{{ ogo1 }} state=directory owner=apache  group=apache mode=0755

- name: Create centos2.com directory for logs
  file: path=/var/log/httpd/{{ ogo2 }} state=directory owner=apache  group=apache mode=0755


  notify:
    - restart httpd

- name: Create web directories for centos1.com VirtualHost
  file: path=/var/www/html/{{ ogo1 }}  state=directory  owner=apache  group=apache  mode=0755

- name: Create web directories for centos2 VirtualHost
  file: path=/var/www/html/{{ ogo2 }}  state=directory  owner=apache  group=apache  mode=0755


  notify:
  - restart httpd
